title: BIRS 2025
author: CTLMath
copyright: "2025"
only_build_toc_files: true
execute:
  execute_notebooks: force
repository:
  url: https://github.com/ctlmath/birs2025
html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false

# ghp-import -n -p -f _build/html